project:
  type: book

book:
  title: "QM2-Tutorium WiSe23/24"
  author: "Raphael Balzer, Emilia Braun"
  date: "9/2/2023"
  search:
    location: sidebar
    type: textbox
  sidebar: 
    logo: QM2-Tutorium_logo.png
    border: false
  navbar:
    left:
      - text: "statistik1"
        href: https://statistik1.netlify.app/
      - text: "start: bayes!"
        href: https://start-bayes.netlify.app/
      - text: "QM1-Tutorium"
        href: https://qm1-tutorium.netlify.app/
      - text: "QM2-Tutorium"
        href: https://qm2-tutorium.netlify.app/
  chapters:
    - index.qmd
    - part: "Aufgaben"
      chapters:
        - Aufg_Wahrscheinlichkeiten.qmd
        - Aufg_Verteilungen.qmd
        - Aufg_Globusversuch.qmd
        - Aufg_Postverteilung.qmd
        - Aufg_Gauss-Modelle.qmd
        - Aufg_Lineare-Modelle.qmd
        - Aufg_Metrische_AV.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    highlight-style: gruvbox
    theme:
      light: minty
      dark: vapor
    df-print: paged
    code-annotations: hover
  pdf:
    documentclass: scrreprt

editor: visual